
################################################
# Which files go in?
# Typically, you would either specify include_files
# or exclude_files
# We use globs instead of regular expressions
################################################

# Here all included files will be defined
# in the corresponding groups below.
include_files = '''
*.js
*.html
manifest.json
'''

exclude_files = '''
f2p.toml
'''

################################################
# Global prompt template
# You can refer to specified variables or
# [[groups]]
# Special variable {files} contains all files
# not yet part of an explicitly included group
################################################
template = '''


# Files of my chrome extension

{{files}}


# Test page

{{test_page}}

# Recorded test workflow

{{test_workflow}}

###########################################################
# YOUR TASK
###########################################################

Above are all files of a chrome extension I am developing.

The extension does not work as expected.

The shown workflow.json shows the record from doing the following on the test_page.html.

1. Start recording
2. Go to the text input enter some text
3. Press "Display Text Below"
4. Press "Log Messages and Cause Error"

Analyse the problem and provide corrected versions only of the files that need change.

'''

###########################################################
# file_template Will be applied to each found file
# and the results will be pasted together
###########################################################

file_template = '''

# FILE: {{filename}}
```
{{filetext}}
```
# END OF FILE: {{filename}}

-----------------------------------------------------------
'''

[[test_page]]

include_files = '''
test_page.html
'''

[[test_workflow]]

include_files = '''
workflow-recording.json
'''
